# Generated by Django 4.2.4 on 2023-09-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerceraEntrega', '0002_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Producto',
        ),
    ]
