# Generated by Django 4.2.5 on 2023-09-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTerceraEntrega', '0005_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.AddField(
            model_name='empleado',
            name='legajo',
            field=models.IntegerField(default=0),
        ),
    ]
